# Dependencies
markdown:         kramdown
highlighter:      rouge

# Gems
gems: ['jekyll-paginate', 'jekyll-gist']

future: true

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Yun Hwan Na
tagline:          '개발 블로그'
description:      '디발자 혹은 개자이너'
url:              https://nayunhwan.github.io
baseurl:          /

author:
  name:           '나윤환'
  url:            http://fb.com/nayunhwan

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
